### ISSUE TITLE
Figtree has display bugs for the 'e'

### ISSUE THREAD

**Issue by erikdkennedy** [DecliningLotus/fontsource#658] opened 2023-03-31 05:31 UTC
### Describe the bug

![figtree-on-fontsource@2x](https://user-images.githubusercontent.com/3440839/229030540-3f970639-deca-43da-a9c7-31020a3c5b62.png)
https://fontsource.org/fonts/figtree
I'm using Brave, Mac OS 10.15.

### Steps to Reproduce

1. Visit https://fontsource.org/fonts/figtree
2. Look at the letter 'e'

### Expected behavior

Should be filled in, but there are gaps – as shown above.

### Version

10.15

### OS

Mac

### Browser

Brave

**Comment by ayuhito** [comment] 2024-12-29 09:59
Closing as I cannot reproduce this on my macOS device now. Variable fonts does fix this cross-platform I believe. Please let me know if I should reopen this.

**Closed as completed by ayuhito** 2024-12-29 09:59 UTC
Labels: bug
